- hosts: all
  become: yes
  roles:

#    - role: docker
#    - role: jenkins
#      when: inventory_hostname in groups['My_Group']
#    - role: slave
#      when: inventory_hostname in groups['Slave']
#    - role: SSHConnection


    - role: docker
      when: inventory_hostname in groups['My_Group']
    - role: kuber
      when: inventory_hostname in groups['My_Group']

#ansible-playbook playbook.yaml --ssh-common-args='-o StrictHostKeyChecking=no'